{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-emt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/EMT_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/EMT/EMT_{{ version }}.tar.gz
  sha256: d971c1a516269b924a8516d409b04dc34d37df43f62ea6128a3c71be584a9a3c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('EMT')"           # [not win]
    - "\"%R%\" -e \"library('EMT')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=EMT
  license: GPL-2.0-or-later
  summary: The package provides functions to carry out a Goodness-of-fit test for discrete multivariate data. It is tested if a given observation is likely to have occurred under the assumption of an ab-initio model. A p-value can be calculated using different distance measures between observed and expected frequencies.
    A Monte Carlo method is provided to make the package capable of solving high-dimensional problems.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
