travis:
  secure:
    BINSTAR_TOKEN: OYjfwA3/ke1yG8Uz14YqGUqUZUefNu+HWAnxnCxEf4Ffs2kkWnNxc72w45JzAjm1RQnIwxqZrRhQ57b/6mP00L2lAxewZiCp6TzgQzM+NZzEiCjE1C1taUnddM+WBNzBIButoGG/lbZqL5GFyLxgO91DVgUXq4P6tqfinwfJuFtTGdjmNrNUXoNuiM/G477llhPt7VlWS9VYB8IIduFoUZFKKfsJI06rWU7yuyGKhcRxpuCdGcnYRC0X/2HI8uR/89grgT4KtjZOf3lIX9m833EpeYd9bWH9XrSQHhhJVB2gKyBJ1n0ub3YL/7UouiDz86CQNmRn4W4cM7RrY5AsNk18fyEbFHNQcralLPJcKS90TCGzMwL4Ra4xdnbwoWPPJAo3Z7BL/BZfrMHpP9hvq++sSleNCpBEYgEO6Mn6U78e2+geB0xkWB8U0qgTlORHcGSsJNtx/ONT1NAniNdKNMnUZ946yqmfY7dMkaSMnLYd7T2yZ6CUkUOPz7DJdw/VlKI6AtkQW9bllft4Nm0kzY13ZKUtu2rOIB9D9OBUsqufwQus+NBiSU49fEo2eIIY3rYaSU4V/8MdOX5TwDb1NGkDYVmS7NFbzukV3SXXgvkkHaYzUltmbbSz390pupxKgpw1sv65Gex0/eQ8wrY/JkFdBGsVCnAqsFD4jtomhX4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
